### ISSUE TITLE
distilleries

### ISSUE THREAD

**Issue by reidch** [johncruickshank/gin#69]
- add distilleries to seeds.js
- create sorting function for distilleries
- add routes

**Comment by PMGH** [comment]
add routes - resolved by commit:  438210a0ad24a2edbc28c9c389792b4563d4b8d2

**Comment by reidch** [comment]
adds 1 distillery to seeds file and adds new distilleries collection to mongodb with commit: e94b9d029e06bfddbc0d2b4a87bdd347b55fba90

**Comment by reidch** [comment]
resolves #69
